name 'nginx'
maintainer 'Francis Pereira'
maintainer_email 'francis@clevertap.com'
license 'all_rights'
description 'Installs/Configures nginx'
long_description 'Installs/Configures nginx'
version '0.1.1'
